### ISSUE TITLE
Not compactible in browser

### ISSUE THREAD

**Issue by antfu** [unjs/pathe#113]
### Environment

Browser

### Reproduction

https://stackblitz.com/edit/vitejs-vite-fyufym?file=main.js&terminal=dev

### Describe the bug

Pathe is referencing `process` and becomes not isomorphic

https://github.com/unjs/pathe/blob/77c0ed10a25e44ca2e6f90a6792a28af5e64cc69/src/path.ts#L84

**Comment by danielroe** [comment]
I think we could resolve this with a node export condition and a slight tweak to the build step.

**Comment by pi0** [comment]
A simple typeof check should be also do the trick :)

**Comment by antfu** [comment]
> A simple typeof check should be also do the trick :)

I am happy to do that, but what should we use on non-node env? `/` or `''`?

**Comment by pi0** [comment]
I think / would be safer for root

**Comment by pi0** [comment]
fixed in 1.0.1 / 1.1.0
