### ISSUE TITLE
module 'pathe' does not provide an export named 'default'

### ISSUE THREAD

**Issue by sheremet-va** [unjs/pathe#115]
### Environment

Any

### Reproduction

https://stackblitz.com/edit/node-wh8ted?file=index.mjs

### Describe the bug

It is possible to use default export with `node:path` module, so I assume since this is a "drop-in" replacement, we should be able to import through default export.

**Comment by pi0** [comment]
fixed in 1.1.0. i hope it works in your setup now :)
