### ISSUE TITLE
`normalize` fails when paths start from drive letter on Windows (e.g. `C:\...`)

### ISSUE THREAD

**Issue by ennioVisco** [unjs/pathe#117]
### Environment

-

### Reproduction

This is an issue first found in `nuxt 3.0.0`, affecting several modules. It's story can be tracked here: https://github.com/nuxt/nuxt/issues/15500

### Describe the bug

-

**Comment by DeivisFelipe** [comment]
Me too with NUXT 3.1.0

**Comment by pi0** [comment]
Can you please provide a pathe reproduction? (IE: example input, current behavior, desired output)

**Comment by dargmuesli** [comment]
@ennioVisco can I help to resolve anything blocking the creation of a reproduction?

**Comment by ennioVisco** [comment]
> @ennioVisco can I help to resolve anything blocking the creation of a reproduction?

Tbh since the issue was not present at nuxt RC, my assumption was, given the hint of the guy to your repo, that the issue was coming from the adoption of pathe in `@nuxt/kit`, sometime between RC and stable release (possibly here: [54da6f81a066aeb6ef862112421122d63559e6d9](https://github.com/nuxt/nuxt/commit/54da6f81a066aeb6ef862112421122d63559e6d9)). 
That said, I tried to revert to that state of the code locally, but I still haven't been able to exactly track the code that actually broke it. So it could be the case that it's not pathe's fault :/

**Comment by dargmuesli** [comment]
I did research and found that this issue arises [when importing an absolute file url on Windows](https://github.com/nodejs/node/issues/31710). It can be resolved by importing `pathToFileUrl(path).href` [as done for `@dargmuesli/nuxt-cookie-module`](https://github.com/dargmuesli/nuxt-cookie-control/pull/57/files#diff-030fc083b2cbf5cf008cfc0c49bb4f1b8d97ac07f93a291d068d81b4d1416f70R113-R114).

I think this issue can be closed as "not planned".

**Comment by ennioVisco** [comment]
The issue is related to bad path resolution from module authors. People encountering this issue in the future should give a look at the suggested modules and at the related nuxt thread: https://github.com/nuxt/nuxt/issues/15500
