### ISSUE TITLE
windows and linux `/`, `\` problem

### ISSUE THREAD

**Issue by productdevbook** [unjs/pathe#138]
import { dirname, join, resolve } from 'pathe'

console.log('a', join('packages/components/'))
linux -> 'packages/components/'
windows -> 'packages/components/'

some problem resolve

but only used 'path' 

linux -> 'packages/components/'
windows -> 'packages\components\'

**Comment by danielroe** [comment]
One of the purposes of this package is to normalise Windows paths to use forward slashes, for consistency between operating systems.
