### ISSUE TITLE
index.mjs importing non-existant module

### ISSUE THREAD

**Issue by aryzing** [unjs/pathe#166]
### Environment

Bun / Node 18

### Reproduction

[repro.webm](https://github.com/unjs/pathe/assets/4924405/f28e2715-d5ab-47f3-ba33-34a39e414f61)

### Describe the bug

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/project-path/node_modules/pathe/dist/shared/pathe.ff20891b.mjs' imported from /project-path/node_modules/pathe/dist/index.mjs
```

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏 

https://unpkg.com/browse/pathe@1.1.2/dist/shared/pathe.ff20891b.mjs

**Comment by aryzing** [comment]
Must have been a one-time installation issue, after deleting node_modules and re-installing, it's there
