### ISSUE TITLE
Question: What's the difference between this and path/posix?

### ISSUE THREAD

**Issue by codepunkt** [unjs/pathe#26]
When using `pathe` on node, what's the difference between this and just importing from `path/posix`?

**Comment by pi0** [comment]
Hi @codepunkt. This library is fully standalone from Node.js and also **handles windows paths**. While path/posix lefts them intact or often unhandled.

**Comment by codepunkt** [comment]
Thanks Pooya! I'm not exactly sure what "handles windows paths" means here.

Nodejs [path docs](https://nodejs.org/api/path.html#windows-vs-posix) says "_To achieve consistent results when working with Windows file paths on any operating system, use [path.win32](https://nodejs.org/api/path.html#pathwin32). To achieve consistent results when working with POSIX file paths on any operating system, use [path.posix](https://nodejs.org/api/path.html#pathposix)_"

Does this mean `pathe` helps get consistent results when working with Windows or POSIX file paths on any operating system, so basically the best of both worlds?
